### ISSUE TITLE
JS IPFS 0.38 release handover

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-core#4]
Friends, now that the [js-ipfs release process improvements](https://github.com/ipfs/js-ipfs/pull/2408) are in the pipeline I can start making arrangements for when I'll be unavailable: 1 month from ~next week.

If we'd started the `0.38` release at the right time the estimated date for shipping would be 17th September. If we're a couple of weeks delayed then I'd still not be back in time to do the release.

Off the top of my head the following needs to happen:

* [x] Finalise feature list for [0.38 release](https://github.com/ipfs/js-ipfs/issues/2396). I've listed a few of items I think we should definitely include and put a `(?)` suffix on items I think we _could_ include but might need some more consideration.
* [x] Choose a volunteer release manager(s) for the `0.38` release - @achingbrain has already said he can help, it might be cool to have a duo? Is anyone else interested in pairing up?
* [x] Ensure release manager(s) have write access to `js-ipfs`, `js-ipfs-http-client` and `interface-js-ipfs-core`
* [x] Release manager(s) need to enable 2FA on npm
* [x] Add release manager(s) as collaborators on npm for `ipfs`, `ipfs-http-client` and `interface-ipfs-core`
* [ ] Walk through the process with the release manager(s)
* ...I missed a thing? Please tell me!

cc @momack

**Comment by hugomrdias** [comment]
I'm also available to help with the release.

**Comment by alanshaw** [comment]
Not explicitly covered above but the release managers on this occasion would also be responsible for day to day [lead maintainer](https://github.com/ipfs/team-mgmt/blob/master/LEAD_MAINTAINER_PROTOCOL.md) duties up to the release but also afterwards until I return!

I've added @achingbrain and @hugomrdias as collaborators on npm, you both have 2FA setup already (good job!) and you're both in the [repos-javascript team](https://github.com/orgs/ipfs/teams/repos-javascript) so you should have write access to the relevant repos.

**Comment by jimpick** [comment]
I'm happy to help out as well! I've only dabbled a bit in the codebase so far though...

**Comment by alanshaw** [comment]
Thanks @achingbrain and @hugomrdias for handling everything while I was away! I came back to it all in a better state than I left it ❤️
